Register Users
its-dev-fer/nanglow-api pull request #4
Opened 2024-08-15 00:43 UTC by Cesars2130

2024-08-15 17:51 UTC, its-dev-fer requested changes

2024-08-15 17:51 UTC, its-dev-fer commented on package.json
>    "license": "ISC",
Tracking: Faltó ejecutar `npm version patch`

2024-08-15 17:51 UTC, its-dev-fer commented on src/auth/auth.controller.ts
> +      const newUserP = {...req.body, permisos : "CLIENTE"}
Minor: Usa el enum de permisos de usuario.

2024-08-15 17:51 UTC, its-dev-fer commented on src/auth/auth.controller.ts
> +      return res.status(200).json({ message: "Usuario creado con éxito", user: newUser });
Status 201

2024-08-15 17:51 UTC, its-dev-fer commented on src/auth/auth.routes.ts
> +
Borra esta línea de más.

2024-08-15 17:51 UTC, its-dev-fer commented on src/index.ts
> +const startServer = async () => {
Puntos extra por el refactor. Considerando que este PR modifica el index, el otro PR abierto deberá sincronizar los cambios.

2024-08-15 17:51 UTC, its-dev-fer commented on src/index.ts
> +        await db.sequelize.sync({ alter: true });
Critical, en producción no se debe usar. Considera agregar lo siguiente:

```ts
if(process.env.PORT.ENVIRONMENT === 'development') await db.sequelize.sync({ alter: true });
```

2024-08-15 17:51 UTC, its-dev-fer commented on src/models/User.ts
> -  @AllowNull(false)
Por qué se borra esta línea?

2024-08-15 17:51 UTC, its-dev-fer commented on src/models/User.ts
> -
Lo mismo para estas dos.

2024-08-15 18:00 UTC, Cesars2130 commented on package.json
>    "license": "ISC",
Listo

2024-08-15 18:02 UTC, Cesars2130 commented on src/auth/auth.controller.ts
> +      const newUserP = {...req.body, permisos : "CLIENTE"}
Listo

2024-08-15 18:03 UTC, Cesars2130 commented on src/index.ts
> +const startServer = async () => {
Aquí tengo que modificar algo entonces?

2024-08-15 18:09 UTC, Cesars2130 commented on src/models/User.ts
> -  @AllowNull(false)
me había comentado que el registro se haría desde la perspectiva del cliente, entonces para que las peticiones puedan pasar desde el front tendríamos que tener la posibilidad que el campo de permisos venga nulo, para así después agregar en el back el permiso de cliente como me dijo.

2024-08-15 18:16 UTC, its-dev-fer commented on src/index.ts
> +const startServer = async () => {
No

2024-08-15 18:17 UTC, its-dev-fer commented on src/models/User.ts
> -  @AllowNull(false)
Bueno, ese @allowNull no es explícitamente del formulario de registo, es más configuración de la base de datos. No se tiene que eliminar.

2024-08-16 14:16 UTC, its-dev-fer approved these changes

2024-08-16 14:17 UTC, merged